config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :musics
  root "musics#index"

  #devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/music.rb
class Music < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
    
    def index
        @musics = Music.all
    end

    def new
        @music = Music.new
      end

      def link_to

      end
    
      def new
        @music = Music.new
      end
    
      def create
        music = Music.new(tweet_params)
        if music.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
    
      private
      def music_params
        params.require(:tweet).permit(:Music_name, :Phrase, :Artist, :comment)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LifeInTunes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

  <body>
 <header>
  <h1><body>

  <main>
</html>

app/views/musics/index.html.erb
<h1>MusicLife</h1>
<h3>一覧ページ</h3>
<%= link_to "新規投稿へ", new_music_path %>
<div class="musics-container">
  <% @musics.each do |t| %>
    <div class="tweet">
      <%= t.Music_name %>
      <%= t.Phrase %>
      <%= t.Artist %>
      <%= t.comment %>
    </div>
  <% end %>

   <header>
   <h1>LifeInTunes</h1>
   <div class="header-list">
    <ul>
     <% if user_signed_in? %>
      <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
     <% else %>
      <li><%= link_to "新規登録", new_user_registration_path %></li>
      <li><%= link_to "ログイン", new_user_session_path %></li>
     <% end %>
    </ul>
   </div>
  </header>
</div>

app/views/musics/new.html.erb
<h1>MusicLife</h1>
<h3>新規music</h3>
<%= form_for @musics do |f| %>
    <div class="field">
    <%= f.label :Music_name %>
    <%= f.text_field :music_name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :Phrase  %>
    <%= f.text_area :phrase, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.label :Artist %>
    <%= f.text_field :カラム名, :size => 30 %>
  </div>

  
  <div class="field">
    <%= f.label :comment  %>
    <%= f.text_area :comment, :size => "30x2" %>
  </div>

  <%= f.submit "musicを投稿する" %>
  <% end %>
  
  <%= link_to "一覧に戻る", musics_path %>
  